on:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate readme
        uses: ./
        with:
          dry_run: yes
          user: ssiyad
          host: havana
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
